/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author celeste
 */
public class AsignacionTarea extends javax.swing.JFrame {

    private Usuario usuario;
    /**
     * Creates new form AsignacionTarea
     */
    public AsignacionTarea(Usuario usuario) {
        initComponents();
        
        this.usuario = usuario;
        CargarProyecto();
        LlenarIdTarea();
    }
    
    public void CargarProyecto()
    {
        int IdEquipo = 0;
        
        //Recorrer la lista de equpos para validar si el usuario logeado es lider de algun equipo
        for(Equipo e: ProyectoFinal.Equipos){
            //Encuentra el usuario dque es lider del equipo
            if(e.getLider().equals(this.usuario.getUsuario())){
                IdEquipo = e.getCorrelativo();
                break;
            }
        }
        
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        for(AsignacionProyectoEquipo pe: ProyectoFinal.AsignacionProyectoEquipos){
            
            if(pe.getIdEquipo() == IdEquipo){
                //Ciclo para recorrer los equipos que se tienen almacenados
                for(Proyecto eq: ProyectoFinal.Proyectos){
                    if(pe.getIdProyecto() == eq.getCorrelativo()) {
                        //Agregar el equipo como elemento del combo
                        modelo.addElement(eq.getNombreProyecto());
                    }                        
                }
            }
            
        }
        
        //Asignar el modelo ya lleno con los usuarios al combo box de la pantalla
        ProyectoComboBox.setModel(modelo);
    }
    
    public void LlenarIdTarea(){
        int IdEquipo = 0;
        
        //Recorrer la lista de equpos para validar si el usuario logeado es lider de algun equipo
        for(Equipo e: ProyectoFinal.Equipos){
            //Encuentra el usuario dque es lider del equipo
            if(e.getLider().equals(this.usuario.getUsuario())){
                IdEquipo = e.getCorrelativo();
                break;
            }
        }
        
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        for(Tarea t: ProyectoFinal.Tareas){  
            for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){ 
                if(eu.getIdEquipo() == IdEquipo){        
                    modelo.addElement(t.getTitulo());
                    break;
                }           
            }
            
        }
        
        TareaComboBox.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProyectoComboBox = new javax.swing.JComboBox<>();
        TareaComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proyecto: ");

        jLabel2.setText("Tarea:");

        ProyectoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        TareaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SalirjButton.setText("Salir");
        SalirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirjButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Asignación de Tarea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProyectoComboBox, 0, 233, Short.MAX_VALUE)
                            .addComponent(TareaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(SalirjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ProyectoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TareaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SalirjButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String TareaL = TareaComboBox.getSelectedItem().toString();
        String ProyectoL = ProyectoComboBox.getSelectedItem().toString();

        //Validar si el combo de equipo no han seleccinado nada
        if(TareaL == "")
        JOptionPane.showMessageDialog(this, "Seleccione una tarea.");
        //Validar si el combo de usuario no han seleccinado nada
        else if(ProyectoL == "")
        JOptionPane.showMessageDialog(this, "Seleccione un proyecto.");

        else {

            int IdTarea = 0;

            //Encontrar Id del proyecto
            for(Tarea p: ProyectoFinal.Tareas){
                if(p.getTitulo().equals(TareaL)){
                    IdTarea = p.getId();
                    break;
                }
            }

            //Validar que el usuario no este asignado a un equipo previamente
            boolean ingresado= false;

            //Recorrer la lista de asgnaciones para validar si el usuario ya esta asignado a un equipo
            for(AsignacionTareaProyecto pe: ProyectoFinal.AsignacionTareasProyetos){
                //Validar si el usuario ya esta asginado
                if(pe.getIdTarea()== IdTarea){
                    ingresado= true;
                    break;
                }
            }

            if(ingresado)
            JOptionPane.showMessageDialog(this, "No se puede guardar porque la tarea ya fue asignada a un proyecto");
            else {

                int IdProyecto = 0;

                //Encontrar Id del proyecto
                for(Proyecto p: ProyectoFinal.Proyectos){
                    if(p.getNombreProyecto().equals(ProyectoL)){
                        IdProyecto = p.getCorrelativo();
                        break;
                    }
                }

                AsignacionTareaProyecto TareaEquipoNuevo = new AsignacionTareaProyecto();
                TareaEquipoNuevo.setIdTarea(IdTarea);
                TareaEquipoNuevo.setIdProyecto(IdProyecto);

                ProyectoFinal.AsignacionTareasProyetos.add(TareaEquipoNuevo);

                TareaComboBox.setSelectedIndex(0);
                ProyectoComboBox.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Tarea asignado al equipo exitosamente");
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void SalirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirjButtonActionPerformed
        // TODO add your handling code here:
        PantallaProyectosGerente inicio = new PantallaProyectosGerente(this.usuario);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirjButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ProyectoComboBox;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JComboBox<String> TareaComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
