/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author celeste
 */
public class AsignacionProyecto extends javax.swing.JFrame {

    /**
     * Creates new form AsignacionProyecto
     */
    public AsignacionProyecto() {
        initComponents();
        CargarEquipos();
        CargarProyecto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        public void CargarProyecto()
    {
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        //Ciclo para recorrer los equipos que se tienen almacenados
        for(Proyecto eq: ProyectoFinal.Proyectos){
            //Agregar el equipo como elemento del combo
            modelo.addElement(eq.getNombreProyecto());
        }
        
        //Asignar el modelo ya lleno con los usuarios al combo box de la pantalla
        ProyectoComboBox.setModel(modelo);
    }
    
     //Funcion para cargar combo de equipos
    public void CargarEquipos()
    {
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        //Ciclo para recorrer los equipos que se tienen almacenados
        for(Equipo eq: ProyectoFinal.Equipos){
            //Agregar el equipo como elemento del combo
            modelo.addElement(eq.getNombreEquipo());
        }
        
        //Asignar el modelo ya lleno con los usuarios al combo box de la pantalla
        EquipoComboBox.setModel(modelo);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProyectoComboBox = new javax.swing.JComboBox<>();
        EquipoComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Asignación de Proyecto");

        jLabel1.setText("Proyecto: ");

        jLabel2.setText("Equipo:");

        ProyectoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        EquipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SalirjButton.setText("Salir");
        SalirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProyectoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EquipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(SalirjButton)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ProyectoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EquipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SalirjButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirjButtonActionPerformed
        // TODO add your handling code here:
        
            PantallaProyectos inicio = new PantallaProyectos();
            inicio.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_SalirjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String EquipoL = EquipoComboBox.getSelectedItem().toString();
        String ProyectoL = ProyectoComboBox.getSelectedItem().toString();
        
           
        //Validar si el combo de equipo no han seleccinado nada
        if(EquipoL == "")
            JOptionPane.showMessageDialog(this, "Seleccione un equipo.");
        //Validar si el combo de usuario no han seleccinado nada
        else if(ProyectoL == "")
            JOptionPane.showMessageDialog(this, "Seleccione un proyecto.");
        
         else {
            
            int IdProyecto = 0;
                    
            //Encontrar Id del proyecto
            for(Proyecto p: ProyectoFinal.Proyectos){
                if(p.getNombreProyecto().equals(ProyectoL)){
                    IdProyecto = p.getCorrelativo();    
                    break;
                }
            }
            
            //Validar que el usuario no este asignado a un equipo previamente
            boolean ingresado= false;
            
            //Recorrer la lista de asgnaciones para validar si el usuario ya esta asignado a un equipo
            for(AsignacionProyectoEquipo pe: ProyectoFinal.AsignacionProyectoEquipos){
                //Validar si el usuario ya esta asginado
                if(pe.getIdProyecto() == IdProyecto){
                    ingresado= true;    
                    break;
                }
            }
            
            if(ingresado)
                JOptionPane.showMessageDialog(this, "No se puede guardar porque el proyecto ya fue asignado a un equipo");
              else {
                
                    int IdEquipo = 0;
                    
                    //Encontrar Id del equipo
                    for(Equipo e: ProyectoFinal.Equipos){
                        if(e.getNombreEquipo().equals(EquipoL)){
                            IdEquipo = e.getCorrelativo();    
                            break;
                        }
                    }
                    
                    AsignacionProyectoEquipo EquipoProyectoNuevo = new AsignacionProyectoEquipo();
                    EquipoProyectoNuevo.setIdEquipo(IdEquipo);
                    EquipoProyectoNuevo.setIdProyecto(IdProyecto);

                    ProyectoFinal.AsignacionProyectoEquipos.add(EquipoProyectoNuevo);

                    EquipoComboBox.setSelectedIndex(0);
                    ProyectoComboBox.setSelectedIndex(0);

                    JOptionPane.showMessageDialog(this, "Proyecto asignado al equipo exitosamente");
                }

        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EquipoComboBox;
    private javax.swing.JComboBox<String> ProyectoComboBox;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
