/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author celeste
 */
public class BienvenidoUsuario extends javax.swing.JFrame {

    
    
    private Usuario usuario;
    /**
     * Creates new form BienvenidoUsuario
     */
    public BienvenidoUsuario(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        NombrejLabel.setText(this.usuario.getNombre());
        ApellidojLabel.setText(this.usuario.getApellido());
        RoljLabel.setText(this.usuario.getRol());
        
        //Recorrer la lista de asgnaciones para validar a que equipo pertenece el usuario
        for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){
            //Encuentra el usuario dentro de las asignaciones, y por ende el equipo
            if(eu.getUsuario().equals(this.usuario.getUsuario())){
                
                String Equipo = "";
                
                for(Equipo e: ProyectoFinal.Equipos){
                    if(e.getCorrelativo() == eu.getIdEquipo()){
                        Equipo = e.getNombreEquipo();    
                        break;
                    }
                }
                
                EquipojLabel.setText(Equipo);
                break;
            }
        }
        
        //Llena la tabla de tareas del miembro
        LlenarJTable();
    }
    
    private void LlenarJTable(){
        
        int Filas = 0;
        
        //Ciclo para contar las tareas que tiene asignadas el usuario
        for(Tarea t: ProyectoFinal.Tareas){ 
            if(t.getUsuarioAsignado().equals(this.usuario.getUsuario())){        
                Filas++;
            } 
        }
        
        DefaultTableModel t = new DefaultTableModel(new String[]{"Codigo Tarea", "Titulo","Fecha Inicio","Ficha Fin","Estado","Proyecto"},Filas);
        jTable1.setModel(t);
        
        TableModel modelo = jTable1.getModel();
        
        int correlativo = 0;
        
        //Ciclo para desplegar datos de las tareas asignadas al miembro en la tabla
        for(Tarea tl: ProyectoFinal.Tareas){  
            
            //Identificar si la tarea esta asignada al usuario logueado
            if(tl.getUsuarioAsignado().equals(this.usuario.getUsuario())){  
                
                modelo.setValueAt(tl.getId(), correlativo, 0);
                modelo.setValueAt(tl.getTitulo(), correlativo, 1);
                modelo.setValueAt(tl.getFechaInicio(), correlativo, 2);
                modelo.setValueAt(tl.getFechaFin(), correlativo, 3);
                modelo.setValueAt(tl.getEstado(), correlativo, 4);

                //Ciclo para determinar a que proyecto esta asignada la tarea
                for(AsignacionTareaProyecto tp: ProyectoFinal.AsignacionTareasProyetos){ 
                    if(tp.getIdTarea()== tl.getId()){  
                        //Ciclo para obtener el nombre del proyecto
                        for(Proyecto pr: ProyectoFinal.Proyectos){
                            if(pr.getCorrelativo() == tp.getIdProyecto()){
                                modelo.setValueAt(pr.getNombreProyecto(), correlativo, 5);
                            }
                        }

                        break;
                    }           
                }

                correlativo++;
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NombrejLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RoljLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ApellidojLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EquipojLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        NombrejLabel.setText("Mi Nombre");

        jLabel3.setText("Rol:");

        RoljLabel.setText("Mi Rol");

        jLabel5.setText("Apellido:");

        ApellidojLabel.setText("Mi Apellido");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("Usuario Miembro:");

        jLabel1.setText("Equipo:");

        EquipojLabel.setText("No se ha asignado a ningun equipo.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoljLabel)
                                    .addComponent(NombrejLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EquipojLabel)
                                    .addComponent(ApellidojLabel)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RoljLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombrejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ApellidojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EquipojLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Obtiene el indice de la fila a la que se le dio click        
        int index = jTable1.getSelectedRow();
        TableModel modelo = jTable1.getModel();
        //obtiene el id de la tarea de la fila que se selecciono
        int CodigoTarea = Integer.parseInt(modelo.getValueAt(index, 0).toString());
        //obtiene el estado de la tarea de la fila que se selecciono
        String EstadoTarea = modelo.getValueAt(index, 4).toString();
        
        //Abre el formulario de cambio de estado, pasandole el id de la tarea y el estado de la tarea seleccionada
        ActualizarEstadoTarea inicio = new ActualizarEstadoTarea(CodigoTarea, EstadoTarea, this.usuario);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidojLabel;
    private javax.swing.JLabel EquipojLabel;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel NombrejLabel;
    private javax.swing.JLabel RoljLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
