/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import static com.mycompany.proyectofinal.ProyectoFinal.Equipos;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;

/**
 *
 * @author celeste
 */
public class CargaEquipos extends javax.swing.JFrame {

    /**
     * Creates new form CargaEquipos
     */
    
    public ArrayList<Equipo> EquiposCargados;
    public ArrayList<AsignacionEquipoUsuario> AsignacionEquiposCarga;
    
    public CargaEquipos() {
        initComponents();
        EquiposCargados = new ArrayList<>();
        AsignacionEquiposCarga = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CargarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("Carga Equipos:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        CargarButton.setText("CARGAR");
        CargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Regresar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(CargarButton)
                        .addGap(0, 383, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CargarButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarButtonActionPerformed
        // TODO add your handling code here:
        
             JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos XML", "xml");
        
        fileChooser.setFileFilter(filtro);
        
        int seleccion = fileChooser.showOpenDialog(this);
        
        //Si seleccionas un archivo entra al if si no no entra
        if(seleccion == JFileChooser.APPROVE_OPTION){
            File archivo = fileChooser.getSelectedFile();
            leerXml(archivo);
        }
        
        
        
    }//GEN-LAST:event_CargarButtonActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        PantallaEquipos equipo = new PantallaEquipos();
        equipo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked
       private void leerXml(File archivo){
        try{
            
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dbBuilder = dbFactory.newDocumentBuilder();
            Document doc = dbBuilder.parse(archivo);
            
            doc.getDocumentElement().normalize();
            
            NodeList nList = doc.getElementsByTagName("Equipo");
            
            for(int i=0; i<nList.getLength();i++){
                
                Node nNode = nList.item(i);
                
                if(nNode.getNodeType() == Node.ELEMENT_NODE){
                    
                      Element e = (Element) nNode;
                      Equipo p = new Equipo();
                      p.setCorrelativo(Integer.parseInt(e.getAttributeNode("id").getTextContent()));
                      p.setNombreEquipo(e.getAttributeNode("NombreEquipo").getTextContent());
                      p.setLider(e.getAttributeNode("Lider").getTextContent());
                      //p.setPrecio(Double.parseDouble(e.getElementsByTagName("precio").item(0).getTextContent()));
                      
                      ProyectoFinal.Equipos.add(p);
                      EquiposCargados.add(p);
                      
                      NodeList miembros = e.getElementsByTagName("miembro");
                      
                      for(int contadorMiembro=0; contadorMiembro<miembros.getLength();contadorMiembro++){
                          Node nMiembro = miembros.item(contadorMiembro);
                          
                          if(nMiembro.getNodeType() == Node.ELEMENT_NODE){
                              Element eMiembro = (Element) nMiembro;
                              
                              AsignacionEquipoUsuario eu = new AsignacionEquipoUsuario();
                              eu.setUsuario(eMiembro.getElementsByTagName("usuario").item(0).getTextContent());
                              eu.setIdEquipo(p.getCorrelativo());
                              
                              ProyectoFinal.AsignacionEquiposUsuarios.add(eu);
                              AsignacionEquiposCarga.add(eu);
                          }
                      }
                      
                }
                
            }
            
            llenarTabla();
            
            
        
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
       
     private void llenarTabla() {
        DefaultTableModel dt = new DefaultTableModel(new String []{"Id","Nombre Equipo","Lider", "Miembro"}, AsignacionEquiposCarga.size());
        
        jTable1.setModel(dt);
        
        TableModel tm = jTable1.getModel();
        
        int Contador = 0;
        
        for(int i = 0; i< EquiposCargados.size();i++){
            Equipo p = EquiposCargados.get(i);            
            
            for (AsignacionEquipoUsuario Asignacion : AsignacionEquiposCarga) {
                if(Asignacion.getIdEquipo() == p.getCorrelativo()){                    
                    tm.setValueAt(p.getCorrelativo(), Contador, 0);
                    tm.setValueAt(p.getNombreEquipo(), Contador, 1);
                    tm.setValueAt(p.getLider(), Contador, 2);
                    tm.setValueAt(Asignacion.getUsuario(), Contador, 3);
                    Contador++;
                }
            }
        }
        
    }  
    

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
