/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author celeste
 */
public class CargaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form CargaUsuarios
     */
    public CargaUsuarios() {
        initComponents();
    }

            
            
          
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        CargajButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setText("Carga Usuarios:");

        CargajButton.setText("CARGAR");
        CargajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargajButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jMenu1.setText("Regresar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(CargajButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CargajButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargajButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter fne = new FileNameExtensionFilter( "Archivo csv separado por pipes","csv");
            jfc.setFileFilter(fne);
            
            int aceptar = jfc.showOpenDialog(this);
            if(aceptar == JFileChooser.APPROVE_OPTION){
            File f = jfc.getSelectedFile();
            String contenido = leerArchivoTexto(f.getPath());
            jTextArea1.setText(contenido);
            
            DefaultTableModel data = new DefaultTableModel(new String[]{"Usuario", "Password", "Correo", "Nombre", "Apellido", "Rol"},ProyectoFinal.Usuarios.size());
            jTable1.setModel(data);
            
            int i = 0;
            for(Usuario u : ProyectoFinal.Usuarios){
                jTable1.setValueAt(u.getUsuario(), i, 0);
                jTable1.setValueAt(u.getPassword(), i, 1);
                jTable1.setValueAt(u.getCorreo(), i, 2);
                jTable1.setValueAt(u.getNombre(), i, 3);
                jTable1.setValueAt(u.getApellido(), i, 4);
                jTable1.setValueAt(u.getRol(), i, 5);
                i++;
                
                
            }
            
        }  
    }//GEN-LAST:event_CargajButtonActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        InicioAdmin inicio = new InicioAdmin();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

      public String leerArchivoTexto(String ruta){
        String contenido = "";
        
        File f = new File(ruta);
        try(
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
           ){
            
            String linea;
            while((linea=br.readLine())!=null){
                contenido+=linea+"\n";
                Usuario u = new Usuario();
                String[] datos = linea.split("\\|");
                u.setUsuario(datos[0]);
                u.setPassword(datos[1]);
                u.setCorreo(datos[2]);
                u.setNombre(datos[3]);
                u.setApellido(datos[4]);
                u.setRol(datos[5]);
                ProyectoFinal.Usuarios.add(u);
            }
            br.close();
            fr.close();
        
        }catch(IOException e){
            System.out.println("Error al leer el archivo");
        }
       
        
        return contenido;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargajButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
