/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author celeste
 */
public class ConsultarAsignacionEquipo extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarAsignacionEquipo
     */
    public ConsultarAsignacionEquipo() {
        initComponents();
        CargarEquipos();
    }
    
    //Funcion para cargar combo de equipos
    public void CargarEquipos()
    {
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        //Ciclo para recorrer los equipos que se tienen almacenados
        for(Equipo eq: ProyectoFinal.Equipos){
            //Agregar el equipo como elemento del combo
            modelo.addElement(eq.getNombreEquipo());
        }
        
        //Asignar el modelo ya lleno con los usuarios al combo box de la pantalla
        EquipoComboBox.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EquipoComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MiembrosTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Equipos:");

        EquipoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EquipoComboBoxItemStateChanged(evt);
            }
        });
        EquipoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setText("Consultar Miembros de Equipo");

        MiembrosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(MiembrosTable);

        jMenu2.setText("Regresar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(EquipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EquipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        PantallaEquipos equipos = new PantallaEquipos();
        equipos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void EquipoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EquipoComboBoxItemStateChanged
        // TODO add your handling code here:
        String EquipoL = EquipoComboBox.getSelectedItem().toString();
        int ContadorFilas = 0;
        int IdEquipo = 0;
                    
        //Encontrar Id del equipo
        for(Equipo e: ProyectoFinal.Equipos){
            if(e.getNombreEquipo().equals(EquipoL)){
                IdEquipo = e.getCorrelativo();    
                break;
            }
        }
        
        //Contar el numero de usuarios que tiene el equipo asignado
        //Recorre todas las asignaciones que se tienen almacenadas
        for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){ 
            //Cuando el equipo sea igual al seleccionado por el combo entrar al if
            if(eu.getIdEquipo() == IdEquipo){        
                //Recorer los usuarios almacenados
                for(Usuario us: ProyectoFinal.Usuarios){
                    //Entra si encontramos el usuario que se encuentra en la asignacion
                    if(us.getUsuario().equals(eu.getUsuario())){
                        //Aumenta el contador de usuarios
                        ContadorFilas++;
                    }
                }
                
            }           
        }
                    
        DefaultTableModel t = new DefaultTableModel(new String[]{"Nombre", "Apellido","Correo",},ContadorFilas);
        MiembrosTable.setModel(t);
        ContadorFilas = 0;
        
        TableModel modelo = MiembrosTable.getModel();
               
        //Recorre todas las asignaciones que se tienen almacenadas
        for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){         
            //Cuando el equipo sea igual al seleccionado por el combo entrar al if
            if(eu.getIdEquipo() == IdEquipo){
                //Recorer los usuarios almacenados
                for(Usuario us: ProyectoFinal.Usuarios){
                    //Entra si encontramos el usuario que se encuentra en la asignacion
                    if(us.getUsuario().equals(eu.getUsuario())){ 
                        //Llena el modelo con los datos del usuario
                        modelo.setValueAt(us.getNombre(), ContadorFilas, 0);
                        modelo.setValueAt(us.getApellido(), ContadorFilas, 1);
                        modelo.setValueAt(us.getCorreo(), ContadorFilas, 2);
                        ContadorFilas++;
                    }
                }
                
            }           
        }
    }//GEN-LAST:event_EquipoComboBoxItemStateChanged

    private void EquipoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EquipoComboBox;
    private javax.swing.JTable MiembrosTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
