/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author celeste
 */
public class CreacionTareas extends javax.swing.JFrame {
    private Usuario usuario;
    /**
     * Creates new form CreacionTareas
     */
    public CreacionTareas(Usuario usuario) {
        initComponents();
        
        this.usuario = usuario;
        
        //Obtener la fecha actual para colocar en los campos de fecha
        Format f = new SimpleDateFormat("dd/MM/yyyy");
        FechaInicioTextField.setText(f.format(new Date()));
        FechaFinjTextField.setText(f.format(new Date()));
        
        //Consultar el numero de equipos existentes y sumarle 1
        CorrelativoLabel.setText(Integer.toString(ProyectoFinal.Tareas.size() + 1));
        
        LlenarMiembro();
    }
    
    public void LlenarMiembro(){
        int IdEquipo = 0;
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        //Recorrer la lista de equpos para validar si el usuario logeado es lider de algun equipo
        for(Equipo e: ProyectoFinal.Equipos){
            //Encuentra el usuario que es lider del equipo
            if(e.getLider().equals(this.usuario.getUsuario())){
                IdEquipo = e.getCorrelativo();
                break;
            }
        }
        
        //Recorre la asignacion de equipos a miembros
        for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){ 
            //Cuando el equipo sea igual al seleccionado por el combo entrar al if
            if(eu.getIdEquipo() == IdEquipo){        
                modelo.addElement(eu.getUsuario());
            }           
        }
        
        jCbxMiembro.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FechaFinjTextField = new javax.swing.JTextField();
        CrearjButton = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CorrelativoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TitulojTextField = new javax.swing.JTextField();
        FechaInicioTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DescripcionjTextField = new javax.swing.JTextField();
        jCbxMiembro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FechaFinjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaFinjTextFieldActionPerformed(evt);
            }
        });

        CrearjButton.setText("Crear");
        CrearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearjButtonActionPerformed(evt);
            }
        });

        SalirjButton.setText("Salir");
        SalirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirjButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Correlativo:");

        CorrelativoLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CorrelativoLabel.setText("0");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Crear Tarea");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Titulo:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Fecha de Inicio:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Fecha de Finalizacion:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setText("Descripcion:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setText("Miembro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbxMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DescripcionjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(TitulojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(FechaInicioTextField)
                                .addComponent(FechaFinjTextField)
                                .addComponent(CorrelativoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(CrearjButton)
                .addGap(58, 58, 58)
                .addComponent(SalirjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CorrelativoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DescripcionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FechaInicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FechaFinjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCbxMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearjButton)
                    .addComponent(SalirjButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FechaFinjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaFinjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaFinjTextFieldActionPerformed

    private void CrearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearjButtonActionPerformed
        // TODO add your handling code here:
        Pattern ExpresionRegular = Pattern.compile("^([0-2][0-9]|3[0-1])(\\/|-)(0[1-9]|1[0-2])\\2(\\d{4})$", Pattern.CASE_INSENSITIVE);
        Matcher CoincidenciaFechaInicio = ExpresionRegular.matcher(FechaInicioTextField.getText());
        boolean ValidarFechaInicio = CoincidenciaFechaInicio.find();
        String Miembro = jCbxMiembro.getSelectedItem().toString();

        if(!ValidarFechaInicio) {
            JOptionPane.showMessageDialog(this, "Ingrese una fecha inicio valida.");
        } else {
            Matcher CoincidenciaFechaFin = ExpresionRegular.matcher(FechaFinjTextField.getText());
            boolean ValidarFechaFin = CoincidenciaFechaFin.find();

            if(!ValidarFechaFin) {
                JOptionPane.showMessageDialog(this, "Ingrese una fecha final valida.");
            } else {

                String Titulo = TitulojTextField.getText();
                String Descripcion = DescripcionjTextField.getText();

                if("".equals(Titulo)) {
                    JOptionPane.showMessageDialog(this, "Ingrese un titulo.");

                } else {
                    
                    if("".equals(Descripcion)){
                        JOptionPane.showMessageDialog(this, "Ingrese una descripcion.");
                    }
                    else{
                        
                        if("".equals(Miembro)){
                            JOptionPane.showMessageDialog(this, "Seleccione un miembro.");
                        } else {
                            Tarea tareaNuevo = new Tarea();
                            tareaNuevo.setTitulo(Titulo);
                            tareaNuevo.setDescripcion(Descripcion);
                            tareaNuevo.setFechaInicio(FechaInicioTextField.getText());
                            tareaNuevo.setFechaFin(FechaFinjTextField.getText());
                            tareaNuevo.setId(Integer.parseInt(CorrelativoLabel.getText()));
                            tareaNuevo.setUsuarioAsignado(Miembro);
                            tareaNuevo.setEstado("Solicitada");
                            
                            ProyectoFinal.Tareas.add(tareaNuevo);
                            
                            TitulojTextField.setText("");
                            DescripcionjTextField.setText("");
                            //Obtener la fecha actual para colocar en los campos de fecha
                            Format f = new SimpleDateFormat("dd/MM/yyyy");
                            FechaInicioTextField.setText(f.format(new Date()));
                            FechaFinjTextField.setText(f.format(new Date()));
                            jCbxMiembro.setSelectedIndex(0);

                            //Consultar el numero de equipos existentes y sumarle 1
                            CorrelativoLabel.setText(Integer.toString(ProyectoFinal.Tareas.size() + 1));

                            JOptionPane.showMessageDialog(this, "Tareas creado exitosamente");
                        }

                    }
                }
            }
        }
    }//GEN-LAST:event_CrearjButtonActionPerformed

    private void SalirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirjButtonActionPerformed
        // TODO add your handling code here:
        PantallaProyectosGerente inicio = new PantallaProyectosGerente(this.usuario);
        inicio.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_SalirjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorrelativoLabel;
    private javax.swing.JButton CrearjButton;
    private javax.swing.JTextField DescripcionjTextField;
    private javax.swing.JTextField FechaFinjTextField;
    private javax.swing.JTextField FechaInicioTextField;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JTextField TitulojTextField;
    private javax.swing.JComboBox<String> jCbxMiembro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
