/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author celeste
 */
public class EditarTareas extends javax.swing.JFrame {

    private Usuario usuario;
    private Tarea TareaModificada;
    /**
     * Creates new form EditarTareas
     */
    public EditarTareas(Usuario usuario) {
        initComponents();
        
        this.usuario = usuario;
        
        LlenarMiembro();
        LlenarIdTarea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalirjButton = new javax.swing.JButton();
        jCbxMiembro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TitulojTextField = new javax.swing.JTextField();
        FechaInicioTextField = new javax.swing.JTextField();
        FechaFinjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CrearjButton = new javax.swing.JButton();
        DescripcionjTextField = new javax.swing.JTextField();
        jCbxTarea = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCbxEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SalirjButton.setText("Salir");
        SalirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirjButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Correlativo:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setText("Miembro:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Modificar Tarea");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("Titulo:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("Fecha de Inicio:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Fecha de Finalizacion:");

        FechaFinjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaFinjTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel7.setText("Descripcion:");

        CrearjButton.setText("Modificar");
        CrearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearjButtonActionPerformed(evt);
            }
        });

        jCbxTarea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbxTareaItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel9.setText("Estado:");

        jCbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solicitada", "En proceso", "Finalizada" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCbxTarea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCbxMiembro, 0, 201, Short.MAX_VALUE)
                            .addComponent(DescripcionjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(TitulojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(FechaInicioTextField)
                            .addComponent(FechaFinjTextField)
                            .addComponent(jCbxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(CrearjButton)
                .addGap(58, 58, 58)
                .addComponent(SalirjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCbxTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DescripcionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FechaInicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FechaFinjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCbxMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearjButton)
                    .addComponent(SalirjButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirjButtonActionPerformed
        // TODO add your handling code here:
        PantallaProyectosGerente inicio = new PantallaProyectosGerente(this.usuario);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirjButtonActionPerformed

    public void LlenarIdTarea(){
        int IdEquipo = 0;
        
        //Recorrer la lista de equpos para validar si el usuario logeado es lider de algun equipo
        for(Equipo e: ProyectoFinal.Equipos){
            //Encuentra el usuario dque es lider del equipo
            if(e.getLider().equals(this.usuario.getUsuario())){
                IdEquipo = e.getCorrelativo();
                break;
            }
        }
        
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        //Encontrar tareas asignadas al equipo al que pertenece el usuario logueado
        for(Tarea t: ProyectoFinal.Tareas){  
            //Recorrer la asignacion de equipos para saber el equipo al que pertenece la tarea
            for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){ 
                if(eu.getIdEquipo() == IdEquipo){        
                    modelo.addElement(Integer.toString(t.getId()));
                    break;
                }           
            }
            
        }
        
        jCbxTarea.setModel(modelo);
    }
    
    public void LlenarMiembro(){
        int IdEquipo = 0;
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        //Recorrer la lista de equpos para validar si el usuario logeado es lider de algun equipo
        for(Equipo e: ProyectoFinal.Equipos){
            //Encuentra el usuario dque es lider del equipo
            if(e.getLider().equals(this.usuario.getUsuario())){
                IdEquipo = e.getCorrelativo();
                break;
            }
        }
        
        for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){ 
            //Cuando el equipo sea igual al seleccionado por el combo entrar al if
            if(eu.getIdEquipo() == IdEquipo){        
                modelo.addElement(eu.getUsuario());
            }           
        }
        
        jCbxMiembro.setModel(modelo);
    }
    
    private void FechaFinjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaFinjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaFinjTextFieldActionPerformed

    private void CrearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearjButtonActionPerformed
        // TODO add your handling code here:
        Pattern ExpresionRegular = Pattern.compile("^([0-2][0-9]|3[0-1])(\\/|-)(0[1-9]|1[0-2])\\2(\\d{4})$", Pattern.CASE_INSENSITIVE);
        Matcher CoincidenciaFechaInicio = ExpresionRegular.matcher(FechaInicioTextField.getText());
        boolean ValidarFechaInicio = CoincidenciaFechaInicio.find();
        String Miembro = jCbxMiembro.getSelectedItem().toString();

        if(!ValidarFechaInicio) {
            JOptionPane.showMessageDialog(this, "Ingrese una fecha inicio valida.");
        } else {
            Matcher CoincidenciaFechaFin = ExpresionRegular.matcher(FechaFinjTextField.getText());
            boolean ValidarFechaFin = CoincidenciaFechaFin.find();

            if(!ValidarFechaFin) {
                JOptionPane.showMessageDialog(this, "Ingrese una fecha final valida.");
            } else {

                String Titulo = TitulojTextField.getText();
                String Descripcion = DescripcionjTextField.getText();

                if("".equals(Titulo)) {
                    JOptionPane.showMessageDialog(this, "Ingrese un titulo.");

                } else {

                    if("".equals(Descripcion)){
                        JOptionPane.showMessageDialog(this, "Ingrese una descripcion.");
                    }
                    else{

                        if("".equals(Miembro)){
                            JOptionPane.showMessageDialog(this, "Seleccione un miembro.");
                        } else {
                            if(TareaModificada !=null){

                                TareaModificada.setTitulo(TitulojTextField.getText());
                                TareaModificada.setDescripcion(DescripcionjTextField.getText());
                                TareaModificada.setFechaInicio(FechaInicioTextField.getText());
                                TareaModificada.setFechaFin(FechaFinjTextField.getText());
                                TareaModificada.setEstado(jCbxEstado.getSelectedItem().toString());
                                TareaModificada.setUsuarioAsignado(Miembro);

                                JOptionPane.showMessageDialog(this, "Tarea modificado exitosamente.");
                            }else{
                                JOptionPane.showMessageDialog(this, "Debe de buscar una tarea");
                            }
                        }

                    }
                }
            }
        }
    }//GEN-LAST:event_CrearjButtonActionPerformed

    private void jCbxTareaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbxTareaItemStateChanged
        // TODO add your handling code here:
        TareaModificada = null; 
        String IdTarea = jCbxTarea.getSelectedItem().toString();
        
        if(!"".equals(IdTarea)){
            //Recorrer la lista de tareas para obtener el objeto a modificar
            for(Tarea u : ProyectoFinal.Tareas){
                if(u.getId() == Integer.parseInt(IdTarea)){
                    TareaModificada = u;
                    break;
                }
            }

            if(TareaModificada !=null){
                TitulojTextField.setText(TareaModificada.getTitulo());
                DescripcionjTextField.setText(TareaModificada.getDescripcion());
                FechaInicioTextField.setText(TareaModificada.getFechaInicio());
                FechaFinjTextField.setText(TareaModificada.getFechaFin());
                jCbxEstado.setSelectedItem(TareaModificada.getEstado());
                jCbxMiembro.setSelectedItem(TareaModificada.getUsuarioAsignado());
            }else{
                JOptionPane.showMessageDialog(this, "Tarea no encontrado");
            }
        }
        
        
    }//GEN-LAST:event_jCbxTareaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearjButton;
    private javax.swing.JTextField DescripcionjTextField;
    private javax.swing.JTextField FechaFinjTextField;
    private javax.swing.JTextField FechaInicioTextField;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JTextField TitulojTextField;
    private javax.swing.JComboBox<String> jCbxEstado;
    private javax.swing.JComboBox<String> jCbxMiembro;
    private javax.swing.JComboBox<String> jCbxTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
