/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author celeste
 */
public class EliminarTarea extends javax.swing.JFrame {

    private Usuario usuario;
    
    /**
     * Creates new form EliminarTarea
     */
    public EliminarTarea(Usuario usuario) {
        initComponents();
        
        this.usuario = usuario;
        LlenarIdTarea();
    }
    
    public void LlenarIdTarea(){
        int IdEquipo = 0;
        
        //Recorrer la lista de equpos para validar si el usuario logeado es lider de algun equipo
        for(Equipo e: ProyectoFinal.Equipos){
            //Encuentra el usuario dque es lider del equipo
            if(e.getLider().equals(this.usuario.getUsuario())){
                IdEquipo = e.getCorrelativo();
                break;
            }
        }
        
        //Creamos un modelo de tipo combo box
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
        
        //Agregamos el elemento inicial que tendra el combo
        modelo.addElement("");
        
        //Encontrar tareas asignadas al equipo al que pertenece el usuario logueado
        for(Tarea t: ProyectoFinal.Tareas){  
            //Recorrer la asignacion de equipos para saber el equipo al que pertenece la tarea
            for(AsignacionEquipoUsuario eu: ProyectoFinal.AsignacionEquiposUsuarios){ 
                if(eu.getIdEquipo() == IdEquipo){        
                    modelo.addElement(t.getTitulo());
                    break;
                }           
            }
            
        }
        
        TareaComboBox.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TareaComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TareaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));

        jLabel2.setText("Tarea:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Eliminar de Tarea");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SalirjButton.setText("Salir");
        SalirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TareaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(SalirjButton)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TareaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SalirjButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String TareaL = TareaComboBox.getSelectedItem().toString();

        //Validar si el combo de equipo no han seleccinado nada
        if(TareaL == "")
            JOptionPane.showMessageDialog(this, "Seleccione una tarea.");
        else {

            int IdTarea = 0;
            int i = -1;
            int indexTarea = -1;

            //Encontrar Id la tarea
            for(Tarea p: ProyectoFinal.Tareas){
                if(p.getTitulo().equals(TareaL)){
                    IdTarea = p.getId();
                    break;
                }
            }

            //Encontrar el indice de la lista de asignacion de tareas a proyectos que se va a eliminar
            for(int j = 0; j<ProyectoFinal.AsignacionTareasProyetos.size(); j++){
                if(ProyectoFinal.AsignacionTareasProyetos.get(j).getIdTarea() == IdTarea){
                    i = j;
                    break;
                }
            }  
            
            if (i>=0)
                ProyectoFinal.AsignacionTareasProyetos.remove(i);
            
            
            for(int jd = 0; jd<ProyectoFinal.Tareas.size(); jd++){
                if(ProyectoFinal.Tareas.get(jd).getId() == IdTarea){
                    indexTarea = jd;
                    break;
                }
            }
            
            if (indexTarea>=0){
                ProyectoFinal.Tareas.remove(indexTarea);
                JOptionPane.showMessageDialog(this, "Tarea eliminada exitosamente.");
                LlenarIdTarea();
            }
            else{
                JOptionPane.showMessageDialog(this, "Tarea no encontrada.");
            }        

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SalirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirjButtonActionPerformed
        // TODO add your handling code here:
        PantallaProyectosGerente inicio = new PantallaProyectosGerente(this.usuario);
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalirjButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalirjButton;
    private javax.swing.JComboBox<String> TareaComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
